# Generated by Django 5.0.6 on 2024-08-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_app', '0002_rename_gamename_topplayer_game_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topplayer',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
    ]
