# Generated by Django 5.0.6 on 2024-09-08 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_app', '0003_topplayer_is_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot_matchID', models.TextField()),
                ('gamelength', models.TextField()),
                ('gametype', models.TextField()),
                ('gameresult', models.TextField()),
                ('top_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lol_app.topplayer')),
            ],
        ),
        migrations.CreateModel(
            name='MatchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_id', models.TextField()),
                ('champion_name', models.TextField()),
                ('kills', models.TextField()),
                ('deaths', models.TextField()),
                ('assists', models.TextField()),
                ('total_damage_dealt', models.TextField()),
                ('total_damage_dealt_tochampions', models.TextField()),
                ('total_damage_taken', models.TextField()),
                ('total_minions_killed', models.TextField()),
                ('gold_earned', models.TextField()),
                ('gold_spent', models.TextField()),
                ('time_ccing_others', models.TextField()),
                ('total_time_cc_dealt', models.TextField()),
                ('getback_pings', models.TextField()),
                ('onmyway_pings', models.TextField()),
                ('needvision_pings', models.TextField()),
                ('push_pings', models.TextField()),
                ('total_time_spent_dead', models.TextField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lol_app.match')),
            ],
        ),
    ]
